# Generated by Django 5.0.6 on 2024-05-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_to_users", to="tasks.task"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
