# Generated by Django 5.0.6 on 2024-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("tasks", "0002_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_to_users", to="tasks.task"
            ),
        ),
    ]
